
### "Get Hello" Production
GET {{prod-host}} 

### "Get Hello" Development
GET {{dev-host}} 



### "Post Hello" Production
POST {{prod-host}}
Content-Type: application/json

{
    "content": "Hello World",
    "notAllowProp": 1931
}

### "Post Hello" Development
POST {{dev-host}}
Content-Type: application/json

{
    "content": "Hello World",
    "notAllowProp": 1931
}