
### Production
GET {{prod-host}}
Content-Type: application/json

{
    "content": "Hello World",
    "notAllowProp": 1931
}

### Development
GET {{dev-host}}
Content-Type: application/json

{
    "content": "Hello World",
    "notAllowProp": 1931
}